import { AppCategory, AppType } from "../../../common";
import { PAGE, DASHBOARD_SCREEN, ALLOW_USER_TYPES } from "../../../router";

export const DASHBOARD_HR_SIDEBAR = [
  {
    key: "job-dashboard",
    title: "Dashboard",
    caption: "Dashboard",
    icon: "group_add",
    path: PAGE.DASHBOARD.path + DASHBOARD_SCREEN.JOB_DASHBOARD.path,
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.JOB_DASHBOARD.allowUserTypes,
  },
  {
    key: "job-list",
    title: "Tin tuyển dụng",
    caption: "Tin tuyển dụng",
    icon: "assignment",
    path: DASHBOARD_SCREEN.JOB.path,
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.JOB.allowUserTypes,
  },
  {
    key: "job-recruitment",
    title: "Danh sách đề xuất",
    caption: "Danh sách đề xuất",
    icon: "assignment_add",
    path: PAGE.DASHBOARD.path + DASHBOARD_SCREEN.JOB_RECRUITMENT.path,
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.JOB_RECRUITMENT.allowUserTypes,
  },
  {
    key: "application-office",
    title: "HSUV Văn Phòng",
    caption: "HSUV Văn Phòng",
    icon: "keyboard",
    path: DASHBOARD_SCREEN.APPLICATION.path,
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.APPLICATION.allowUserTypes,
  },
  {
    key: "application-operator",
    title: "Hồ sơ Thợ Kim Hoàn",
    caption: "Hồ sơ Thợ Kim Hoàn",
    icon: "factory",
    path: DASHBOARD_SCREEN.APPLICATION_OPERATOR.path,
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.APPLICATION_OPERATOR.allowUserTypes,
  },
  {
    key: "job-social",
    title: "Mạng xã hội",
    caption: "Mạng xã hội",
    icon: "globe_asia",
    path: DASHBOARD_SCREEN.JOB_SOCIAL.path,
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.JOB_SOCIAL.allowUserTypes,
  },
  {
    key: "job-management",
    title: "Thiết lập",
    caption: "Thiết lập",
    icon: "settings",
    category: AppCategory.HRM,
    allowUserTypes: ALLOW_USER_TYPES,
    type: AppType.EXPAND_MENU,
    children: [
      {
        key: "job-categories",
        title: "DANH MỤC",
        caption: "DANH MỤC",
        icon: "mobile_layout",
        category: AppCategory.HRM,
        allowUserTypes: ALLOW_USER_TYPES,
        children: [
          {
            key: "job-title",
            title: "Chức danh",
            caption: "Chức danh",
            icon: "photo_camera_front",
            path: DASHBOARD_SCREEN.JOB_TITLE.path,
            category: AppCategory.HRM,
            allowUserTypes: DASHBOARD_SCREEN.JOB_TITLE.allowUserTypes,
          },
          {
            key: "industry",
            title: "Ngành nghề",
            caption: "Ngành nghề",
            icon: "tv_options_input_settings",
            path: DASHBOARD_SCREEN.INDUSTRY.path,
            category: AppCategory.HRM,
            allowUserTypes: DASHBOARD_SCREEN.INDUSTRY.allowUserTypes,
          },
          {
            key: "salary",
            title: "Khung lương",
            caption: "Khung lương",
            icon: "attach_money",
            path: DASHBOARD_SCREEN.SALARY.path,
            category: AppCategory.HRM,
            allowUserTypes: DASHBOARD_SCREEN.SALARY.allowUserTypes,
          },
          {
            key: "email-template",
            title: "Mẫu email",
            caption: "Mẫu email",
            icon: "Email",
            path: DASHBOARD_SCREEN.EMAIL_TEMPLATE.path,
            category: AppCategory.HRM,
            allowUserTypes: DASHBOARD_SCREEN.EMAIL_TEMPLATE.allowUserTypes,
          },
          {
            key: "job-recruitment-history",
            title: "Lịch sử yêu cầu",
            caption: "Lịch sử yêu cầu",
            icon: "history",
            path: DASHBOARD_SCREEN.JOB_RECRUITMENT_HISTORY.path,
            category: AppCategory.HRM,
            allowUserTypes:
              DASHBOARD_SCREEN.JOB_RECRUITMENT_HISTORY.allowUserTypes,
          },
        ],
      },
      {
        key: "job-website",
        title: "Website",
        caption: "Website",
        icon: "language",
        category: AppCategory.HRM,
        allowUserTypes: DASHBOARD_SCREEN.JOB_BANNER.allowUserTypes,
        children: [
          {
            key: "job-banner",
            title: "Banner",
            caption: "Banner",
            icon: "panorama",
            path: DASHBOARD_SCREEN.JOB_BANNER.path,
            category: AppCategory.HRM,
            allowUserTypes: DASHBOARD_SCREEN.JOB_BANNER.allowUserTypes,
          },
          {
            key: "faq",
            title: "Câu hỏi",
            caption: "Câu hỏi",
            icon: "HelpOutline",
            path: DASHBOARD_SCREEN.FAQ.path,
            category: AppCategory.HRM,
            allowUserTypes: DASHBOARD_SCREEN.FAQ.allowUserTypes,
          },
        ],
      },
    ],
  },
];

export const DASHBOARD_HRM_SIDEBAR = [
  {
    key: "user-management",
    title: "Nhân sự",
    caption: "Nhân sự",
    icon: "PersonOutlined",
    path: PAGE.DASHBOARD.path + DASHBOARD_SCREEN.USER.path,
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.USER.allowUserTypes,
  },
  {
    key: "user-management-restore",
    title: "Thiết lập",
    caption: "Thiết lập",
    icon: "settings",
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.SALARY.allowUserTypes,
    type: AppType.EXPAND_MENU,
    children: [
      {
        key: "user-categories",
        title: "DANH MỤC",
        caption: "DANH MỤC",
        icon: "mobile_layout",
        category: AppCategory.HRM,
        allowUserTypes: DASHBOARD_SCREEN.SALARY.allowUserTypes,
        children: [
          {
            key: "user-restore",
            title: "Khôi phục dữ liệu",
            caption: "Khôi phục dữ liệu",
            icon: "restore",
            path: DASHBOARD_SCREEN.USER_RESTORE.path,
            category: AppCategory.HRM,
            allowUserTypes: DASHBOARD_SCREEN.USER_RESTORE.allowUserTypes,
          },
        ],
      },
    ],
  },
];

export const DASHBOARD_TREE_SYSTEM_SIDEBAR = [
  {
    key: "org-structure",
    title: "Sơ đồ tổ chức",
    caption: "Sơ đồ tổ chức",
    icon: "graph_3",
    path: PAGE.DASHBOARD.path + DASHBOARD_SCREEN.ORG_STRUCTURE.path,
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.ORG_STRUCTURE.allowUserTypes,
  },
  {
    key: "org-unit",
    title: "Sơ đồ phòng ban",
    caption: "Sơ đồ phòng ban",
    icon: "graph_1",
    path: DASHBOARD_SCREEN.ORG_UNIT_TREE.path,
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.ORG_UNIT_TREE.allowUserTypes,
  },
  {
    key: "position",
    title: "Sơ đồ chức vụ",
    caption: "Sơ đồ chức vụ",
    icon: "graph_2",
    path: DASHBOARD_SCREEN.POSITION_TREE.path,
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.POSITION_TREE.allowUserTypes,
  },
  {
    key: "user-title",
    title: "Danh sách chức danh",
    caption: "Danh sách chức danh",
    icon: "group",
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.POSITION_TREE.allowUserTypes,
    type: AppType.EXPAND_MENU,
    children: [
      {
        key: "user-titles-restore",
        title: "DANH MỤC",
        caption: "DANH MỤC",
        icon: "mobile_layout",
        category: AppCategory.HRM,
        allowUserTypes: DASHBOARD_SCREEN.POSITION_TREE.allowUserTypes,
        children: [
          {
            key: "user-titles",
            title: "Thiết lập chức danh",
            caption: "Thiết lập chức danh",
            icon: "restore",
            path: DASHBOARD_SCREEN.USER_TITLE.path,
            category: AppCategory.HRM,
            allowUserTypes: DASHBOARD_SCREEN.USER_TITLE.allowUserTypes,
          },
          {
            key: "user-permissions",
            title: "Thiết lập phân quyền",
            caption: "Thiết lập phân quyền",
            icon: "restore",
            path: DASHBOARD_SCREEN.USER_UP_PERMISSIONS.path,
            category: AppCategory.HRM,
            allowUserTypes: DASHBOARD_SCREEN.USER_UP_PERMISSIONS.allowUserTypes,
          },
        ],
      },
    ],
  },
  {
    key: "management-restore1",
    title: "Thiết lập",
    caption: "Thiết lập",
    icon: "settings",
    category: AppCategory.HRM,
    allowUserTypes: DASHBOARD_SCREEN.POSITION_TREE.allowUserTypes,
    type: AppType.EXPAND_MENU,
    children: [
      {
        key: "org-management-restore",
        title: "DANH MỤC",
        caption: "DANH MỤC",
        icon: "mobile_layout",
        category: AppCategory.HRM,
        allowUserTypes: DASHBOARD_SCREEN.POSITION_TREE.allowUserTypes,
        children: [
          {
            key: "org-unit-restore",
            title: "Khôi phục phòng ban",
            caption: "Khôi phục phòng ban",
            icon: "restore",
            path: DASHBOARD_SCREEN.ORG_UNIT_RESTORE.path,
            category: AppCategory.HRM,
            allowUserTypes: DASHBOARD_SCREEN.ORG_UNIT_RESTORE.allowUserTypes,
          },
          {
            key: "position-restore",
            title: "Khôi phục chức vụ",
            caption: "Khôi phục chức vụ",
            icon: "restore",
            path: DASHBOARD_SCREEN.POSITION_RESTORE.path,
            category: AppCategory.HRM,
            allowUserTypes: DASHBOARD_SCREEN.POSITION_RESTORE.allowUserTypes,
          },
        ],
      },
    ],
  },
];
