import { UserType } from "../../apis/user/user.enum";
import {
  DASHBOARD_HR_SIDEBAR,
  DASHBOARD_HRM_SIDEBAR,
  DASHBOARD_TREE_SYSTEM_SIDEBAR,
} from "../../pages";
import {
  ALLOW_USER_TYPES,
  DASHBOARD_SCREEN,
  PAGE,
  WORKFLOW_ENGINE_SCREEN,
  WORKFLOW_TRACKING_SCREEN,
} from "../../router/route.constant";
import { AppCategory, AppModule, AppType } from "../enums/app-category.enum";

// Định nghĩa tất cả các module/apps của hệ thống
export const SYSTEM_MODULES: AppModule[] = [
  {
    key: "sevago-e-hiring",
    title: "Sevago E-Hiring",
    caption: "Tuyển Dụng",
    icon: "/images/system/sevago-e-hiring.svg",
    path: PAGE.DASHBOARD.path + DASHBOARD_SCREEN.JOB_DASHBOARD.path,
    category: AppCategory.HRM,
    allowUserTypes: [
      UserType.ADMIN,
      UserType.User,
      UserType.C_B,
      UserType.HR,
      UserType.ROOT,
    ],
    children: DASHBOARD_HR_SIDEBAR,
  },
  {
    key: "sevago-hrm",
    title: "Sevago HRM",
    caption: "Nhân Sự",
    icon: "/images/system/sevago-hrm.svg",
    path: PAGE.DASHBOARD.path + DASHBOARD_SCREEN.USER.path,
    category: AppCategory.HRM,
    allowUserTypes: ALLOW_USER_TYPES,
    children: DASHBOARD_HRM_SIDEBAR,
  },
  {
    key: "sevago-payroll",
    title: "Sevago Payroll",
    caption: "Tính Lương",
    icon: "/images/system/sevago-payroll.svg",
    path: DASHBOARD_SCREEN.PAYROLL.path,
    category: AppCategory.HRM,
    allowUserTypes: [UserType.ADMIN, UserType.HR, UserType.ROOT],
    children: [
      {
        key: "sevago-payroll-user",
        title: "Tính lương",
        caption: "Payroll",
        icon: "graph_3",
        path: DASHBOARD_SCREEN.PAYROLL.path,
        category: AppCategory.HRM,
        allowUserTypes: DASHBOARD_SCREEN.PAYROLL.allowUserTypes,
      },
    ],
  },
  {
    key: "sevago-chart",
    title: "Sevago Sơ đồ",
    caption: "Sơ đồ",
    icon: "/images/system/sevago-chart.svg",
    path: DASHBOARD_SCREEN.ORG_STRUCTURE.path,
    category: AppCategory.HRM,
    allowUserTypes: ALLOW_USER_TYPES,
    children: DASHBOARD_TREE_SYSTEM_SIDEBAR,
  },
  {
    key: "sevago-checkin",
    title: "Sevago Checkin",
    caption: "Chấm Công",
    icon: "/images/system/sevago-checkin.svg",
    path: DASHBOARD_SCREEN.CHECK_IN.path,
    category: AppCategory.HRM,
    allowUserTypes: ALLOW_USER_TYPES,
    children: [
      {
        key: "sevago-check-in",
        title: "Check-in",
        caption: "Check-in",
        icon: "graph_3",
        path: DASHBOARD_SCREEN.CHECK_IN.path,
        category: AppCategory.HRM,
        allowUserTypes: DASHBOARD_SCREEN.CHECK_IN.allowUserTypes,
      },
    ],
  },
  {
    key: "sevago-project",
    title: "Sevago Project",
    caption: "Dự Án",
    icon: "/images/system/sevago-project.svg",
    path: PAGE.DASHBOARD.path + DASHBOARD_SCREEN.PROJECT_TASK.path,
    category: AppCategory.WORKFLOW,
    allowUserTypes: ALLOW_USER_TYPES,
    children: [
      {
        key: "project-list",
        title: "Danh sách dự án",
        caption: "Danh sách dự án",
        icon: "folder_copy",
        path: PAGE.DASHBOARD.path + DASHBOARD_SCREEN.PROJECT_TASK.path,
        category: AppCategory.WORKFLOW,
        allowUserTypes: DASHBOARD_SCREEN.PROJECT_TASK.allowUserTypes,
      },
      {
        key: "project-chart",
        title: "Biểu đồ",
        caption: "Biểu đồ",
        icon: "timeline",
        path: DASHBOARD_SCREEN.PROJECT_TASK_PROCESS.path,
        category: AppCategory.WORKFLOW,
        allowUserTypes: DASHBOARD_SCREEN.PROJECT_TASK_PROCESS.allowUserTypes,
        type: AppType.SUBMENU,
        children: [
          {
            key: "project-process",
            title: "Biểu đồ tiến độ",
            caption: "Biểu đồ tiến độ",
            icon: "timeline",
            path: DASHBOARD_SCREEN.PROJECT_TASK_PROCESS.path,
            category: AppCategory.WORKFLOW,
            allowUserTypes:
              DASHBOARD_SCREEN.PROJECT_TASK_PROCESS.allowUserTypes,
          },
          {
            key: "project-dashboard",
            title: "Tổng quan dự án",
            caption: "Tổng quan dự án",
            icon: "bar_chart_4_bars",
            path: DASHBOARD_SCREEN.PROJECT_DASHBOARD.path,
            category: AppCategory.WORKFLOW,
            allowUserTypes: DASHBOARD_SCREEN.PROJECT_DASHBOARD.allowUserTypes,
          },
        ],
      },
      {
        key: "task-to-me",
        title: "Công việc của tôi",
        caption: "Công việc của tôi",
        icon: "assignment_ind",
        path: PAGE.DASHBOARD.path + DASHBOARD_SCREEN.TASK_OF_ME.path,
        category: AppCategory.WORKFLOW,
        allowUserTypes: DASHBOARD_SCREEN.TASK_OF_ME.allowUserTypes,
      },
    ],
  },
  {
    key: "sevago-request",
    title: "Sevago Request",
    caption: "Đề Xuất",
    icon: "/images/system/sevago-request.svg",
    path:
      PAGE.WORKFLOW_ENGINE.path +
      WORKFLOW_ENGINE_SCREEN.PROPOSAL_JOB_RECRUITMENT.path,
    category: AppCategory.WORKFLOW,
    allowUserTypes: ALLOW_USER_TYPES,
  },
  {
    key: "sevago-process",
    title: "Sevago Process",
    caption: "Quy trình",
    icon: "/images/system/sevago.svg",
    path: PAGE.NOT_FOUND.path,
    category: AppCategory.WORKFLOW,
    allowUserTypes: ALLOW_USER_TYPES,
  },
  {
    key: "sevago-tracking",
    title: "Sevago Tracking",
    caption: "Tiến trình",
    icon: "/images/system/sevago.svg",
    path: PAGE.WORKFLOW_TRACKING.path + WORKFLOW_TRACKING_SCREEN.MY_TASK.path,
    category: AppCategory.WORKFLOW,
    allowUserTypes: ALLOW_USER_TYPES,
  },

  {
    key: "sevago-message",
    title: "Sevago Message",
    caption: "Chat nhóm",
    icon: "/images/system/sevago-message.svg",
    path: DASHBOARD_SCREEN.CHAT.path,
    category: AppCategory.PLATFORM_INFO,
    allowUserTypes: ALLOW_USER_TYPES,
  },
  {
    key: "sevago-training",
    title: "Sevago Training",
    caption: "Đào Tạo",
    icon: "/images/system/sevago-training.svg",
    path: DASHBOARD_SCREEN.TRAINING.path,
    category: AppCategory.PLATFORM_INFO,
    allowUserTypes: ALLOW_USER_TYPES,
    children: [
      {
        key: "sevago-training-user",
        title: "Đào tạo",
        caption: "Training",
        icon: "graph_3",
        path: DASHBOARD_SCREEN.TRAINING.path,
        category: AppCategory.HRM,
        allowUserTypes: DASHBOARD_SCREEN.TRAINING.allowUserTypes,
      },
    ],
  },
  {
    key: "sevago-form",
    title: "Sevago Form",
    caption: "Biểu mẫu",
    icon: "/images/system/sevago-form.svg",
    path: PAGE.NOT_FOUND.path,
    category: AppCategory.PLATFORM_INFO,
    allowUserTypes: ALLOW_USER_TYPES,
  },
  {
    key: "sevago-inside",
    title: "Sevago Inside",
    caption: "Truyền Thông và CSNV",
    icon: "/images/system/sevago-inside.svg",
    path: DASHBOARD_SCREEN.INSIDE.path,
    category: AppCategory.PLATFORM_INFO,
    allowUserTypes: ALLOW_USER_TYPES,
    children: [
      {
        key: "sevago-inside-user",
        title: "Truyền thông",
        caption: "Inside",
        icon: "graph_3",
        path: DASHBOARD_SCREEN.INSIDE.path,
        category: AppCategory.HRM,
        allowUserTypes: DASHBOARD_SCREEN.INSIDE.allowUserTypes,
      },
    ],
  },
  {
    key: "sevago-booking",
    title: "Sevago Booking",
    caption: "Cuộc họp",
    icon: "/images/system/sevago-inside.svg",
    path: PAGE.BOOKING.path,
    // path: PAGE.NOT_FOUND.path,
    category: AppCategory.PLATFORM_INFO,
    allowUserTypes: ALLOW_USER_TYPES,
  },
];
