import { APP_GROUP_COLOR, AppGroup, AppInfo } from "./apps.data";
import {
  sevagoChartIcon,
  sevagoCheckinIcon,
  sevagoEHiringIcon,
  sevagoFormIcon,
  sevagoHrmIcon,
  sevagoIcon,
  sevagoInsideIcon,
  sevagoMessageIcon,
  sevagoPayrollIcon,
  sevagoProjectIcon,
  sevagoRequestIcon,
  sevagoTrainingIcon,
} from "./icons.constant";

// Định nghĩa tất cả các module/apps của hệ thống
export const SYSTEM_MODULES: AppInfo[] = [
  {
    path: "sevago-e-hiring",
    content: "Sevago E-Hiring",
    icon: sevagoEHiringIcon,
    group: AppGroup.HRM,
    color: APP_GROUP_COLOR[AppGroup.HRM],
  },
  {
    path: "sevago-hrm",
    content: "Sevago HRM",
    icon: sevagoHrmIcon,
    group: AppGroup.HRM,
    color: APP_GROUP_COLOR[AppGroup.HRM],
  },
  {
    path: "sevago-payroll",
    content: "Sevago Payroll",
    icon: sevagoPayrollIcon,
    group: AppGroup.HRM,
    color: APP_GROUP_COLOR[AppGroup.HRM],
  },
  {
    path: "sevago-chart",
    content: "Sevago Sơ đồ",
    icon: sevagoChartIcon,
    group: AppGroup.HRM,
    color: APP_GROUP_COLOR[AppGroup.HRM],
  },
  {
    path: "sevago-checkin",
    content: "Sevago Checkin",
    icon: sevagoCheckinIcon,
    group: AppGroup.HRM,
    color: APP_GROUP_COLOR[AppGroup.HRM],
  },
  {
    path: "sevago-project",
    content: "Sevago Project",
    icon: sevagoProjectIcon,
    group: AppGroup.WORKFLOW_ENGINE,
    color: APP_GROUP_COLOR[AppGroup.WORKFLOW_ENGINE],
  },
  {
    path: "sevago-request",
    content: "Sevago Request",
    icon: sevagoRequestIcon,
    group: AppGroup.WORKFLOW_ENGINE,
    color: APP_GROUP_COLOR[AppGroup.WORKFLOW_ENGINE],
  },
  {
    path: "sevago-process",
    content: "Sevago Process",
    icon: sevagoIcon,
    group: AppGroup.WORKFLOW_ENGINE,
    color: APP_GROUP_COLOR[AppGroup.WORKFLOW_ENGINE],
  },
  {
    path: "sevago-tracking",
    content: "Sevago Tracking",
    icon: sevagoIcon,
    group: AppGroup.WORKFLOW_ENGINE,
    color: APP_GROUP_COLOR[AppGroup.WORKFLOW_ENGINE],
  },

  {
    path: "sevago-message",
    content: "Sevago Message",
    icon: sevagoMessageIcon,
    group: AppGroup.PLATFORM_AND_INFO,
    color: APP_GROUP_COLOR[AppGroup.PLATFORM_AND_INFO],
  },
  {
    path: "sevago-training",
    content: "Sevago Training",
    icon: sevagoTrainingIcon,
    group: AppGroup.PLATFORM_AND_INFO,
    color: APP_GROUP_COLOR[AppGroup.PLATFORM_AND_INFO],
  },
  {
    path: "sevago-form",
    content: "Sevago Form",
    icon: sevagoFormIcon,
    group: AppGroup.PLATFORM_AND_INFO,
    color: APP_GROUP_COLOR[AppGroup.PLATFORM_AND_INFO],
  },
  {
    path: "sevago-inside",
    content: "Sevago Inside",
    icon: sevagoInsideIcon,
    group: AppGroup.PLATFORM_AND_INFO,
    color: APP_GROUP_COLOR[AppGroup.PLATFORM_AND_INFO],
  },
  {
    path: "sevago-booking",
    content: "Sevago Booking",
    icon: sevagoInsideIcon,
    group: AppGroup.PLATFORM_AND_INFO,
    color: APP_GROUP_COLOR[AppGroup.PLATFORM_AND_INFO],
  },
];
